### PR TITLE
Updated Haskell Platform section of the Downloads page.

### PR DESCRIPTION
**Pull request by erantapaa**
This change will work with either the existing Haskell Platform web pages or the new ones which we will install after 7.10.2 is released.

### CODE REVIEW

**Comment by gbaz** [comment]
I feel we have to leave some version of the hedge language in there until community consensus emerges (which I suspect will be with the next HP, which is minimal and includes stack, and not this one, which as I understand it there will still be concerns about).

**Comment by mzero** [comment]
If you want to express multiple views, let's do so in the positive. That is, rather than have the HP section steer people away from it, add positive language to the other section.

**Comment by gbaz** [comment]
How about, parallel to the blurb below the HP headder add a blurb below "Compiler and Base libraries" like so:

"Many now recommend just using the compiler and base libraries combined with package sandboxing, especially for new users interested in using frameworks with complex dependency structures."

?

**Comment by mzero** [comment]
Seems reasonable to me.

**Comment by erantapaa** [comment]
PR has been updated with Gershom's suggested text for the "Compiler and Libraries" download section.

**Comment by gbaz** [comment]
looks good to me.

**Pull request merged**
