### PR TITLE
This site is, like, so 2015.

### PR DESCRIPTION
**Pull request by shiroginne**
😁

### CODE REVIEW

**Comment by relrod** [comment]
(I am not a lawyer)

Thanks for the PR! :smile:

The copyright year is the start date of the copyright which will be covered for the next N years (where N depends on country and such). So I don't think we have to bump it every year, only if we made substantial changes to the site. This means if we bump the copyright year, we're no longer claiming copyright for the original date, and if somebody copies the work and claims it is theirs (because they published it before the date we now claim), then it would be harder to determine who is the original creator of the content.

Therefore, something like "2015, 2016" might be better -- but even this I think we only need to do if there is a substantial revision in the year we're appending.

But again, I'm not a lawyer, maybe someone on the Haskell committee can chime in. I'm going to leave this open and hold off on merging for right now (if someone else wants to, they can, but I'd like to get a second opinion first).

**Comment by relrod** [comment]
Hm, on second glance, we already use a date range there. It seems weird to me to put an upper bound on the copyright like that. *shrug*

**Comment by shiroginne** [comment]
I’m not a lawyer also, just guided by the fact that other programming languages sites have current year in the footer e.g https://clojure.org/, http://elixir-lang.org/ 😅

**Comment by chrisdone** [comment]
@relrod I agree, I originally put the date that the content was created. Someone made a PR to put a range in there in 2015 and thus begins the cycle of tradition.

**Comment by relrod** [comment]
@chrisdone Looks like it was my fault (https://github.com/haskell-infra/hl/compare/dab601de2e5ca3241cea75c47c54e9a595cf1302%5E%5E...dab601de2e5ca3241cea75c47c54e9a595cf1302) -- I wish I referenced the actual discussion that took place in that commit, because I'm pretty sure the range isn't the right thing to do now.

**Comment by gbaz** [comment]
changed w/ redesign

**Pull request closed without merging**
