### PR TITLE
Add HLHT

### PR DESCRIPTION
**Pull request by GetContented**
Add HLHT

### CODE REVIEW

**Comment by gbaz** [comment]
Hi. Sorry for the late reply. We started a thread on this on the haskell-community list and some questions were asked, if you want to join the list and reply there. https://mail.haskell.org/pipermail/haskell-community/2016-April/000103.html

Otherwise feel free to reply in ticket and I can forward.

**Comment by GetContented** [comment]
Thanks.

I added myself to the list and replied, but the email I added is a general one and the one I replied from is my juilan@getcontented.com.au <mailto:juilan@getcontented.com.au> address.

Sorry if that’s caused you any annoyance.

Julian (for GetContented)

http://www.getcontented.com.au/ <http://www.getcontented.com.au/> - Amazing website creation service. Get a professional, distinguished yet highly affordable website today.
http://www.happylearnjavascripttutorial.com/ <http://www.happylearnjavascripttutorial.com/> - begin programming with JavaScript today using our awesome new method!
http://www.happylearnhaskelltutorial.com/ <http://www.happylearnhaskelltutorial.com/> - begin programming with Haskell today using our awesome new method!

**Comment by GetContented** [comment]
@gbaz this seems to have stagnated (on the list). Or, are we just being impatient? :)

**Comment by gbaz** [comment]
Yep, it's stalled. I think that means nobody objects, so merging. Thanks!

**Comment by GetContented** [comment]
Awesome. Thanks very much!

**Pull request merged**
