### PR TITLE
Change 'advanced purely-functional language' to 'general-purpose purely-functional language'

### PR DESCRIPTION
**Pull request by jeffersoncarpenter**
It'll give non-Haskell programmers a warmer first impression when they wander onto the site.

### CODE REVIEW

**Comment by gbaz** [comment]
I don't really buy the motivation here. I don't think "advanced" sounds that scary.

**Comment by jeffersoncarpenter** [comment]
I don't think "advanced" sounds scary either.

Haskell is a great language to start new projects in.  Better than Java or Python or any other dinosaur language out there.  It has a lot of good libraries, and the community is sizeable and helpful.

The '98 report calls Haskell a "general-purpose, purely-functional programming language" (https://www.haskell.org/onlinereport/intro.html)

I think "advanced, purely-functional" is redundant.  Purely-functional is a good example of advanced.  The text in the 98 report hits the nail on the head.  Haskell is both advanced and general-purpose.  This is why it's doomed to succeed.  But not if the tagline on the website only tells half the story >:]

**Comment by chrisdone** [comment]
Ambivalent; existing text is fine, following the Haskell report also works for me.

**Comment by jeffersoncarpenter** [comment]
Is there anyone besides the owners of this github repository who would have to approve this change?

**Comment by jeffersoncarpenter** [comment]
What would be a good approval procedure for this kind of change?

**Comment by gbaz** [comment]
We went round and round on this on irc a while ago and I think talked ourself into a circle. In any case, the decision is it is going to stay the way it is for the time being, since there isn't a general sentiment that 'advanced' is offputting, nor a sentiment that we need to underline 'general purpose' anymore, and 'a purely-functional programming language' on its own is sort of not very exciting.

**Comment by jeffersoncarpenter** [comment]
Agreed.  We talked on IRC about some alternatives, and made a decision to leave it as it is.

**Pull request closed without merging**
