### PR TITLE
Retrieve wiki pages via MediaWiki API

### PR DESCRIPTION
**Pull request by mgrabovsky**
Change URL in `HL.Model.Wiki` to fetch wiki pages through the MediaWiki API instead
of the hackish Special:Export way

### CODE REVIEW

**Comment by chrisdone** [comment]
Oo la la, I had no idea that API existed. I'll test this.

**Comment by chrisdone** [comment]
Very cool, dude! Merged. This'll be deployed once the sysadmins in the US wake up.

**Comment by mgrabovsky** [comment]
As a sidenote, it would be optimal to have a custom skin for MediaWiki (or an entirely different wiki software) in place of this juggling with HTTP and Pandoc.

**Comment by chrisdone** [comment]
Yes, that's not what /wiki was made for.

**Pull request closed without merging**
