### PR TITLE
Update linux-install.md

### PR DESCRIPTION
**Pull request by whossname**
I think this line broke my PATH variable. It might be a bit of a pain fixing it now ...

### CODE REVIEW

**Comment by glguy** [comment]
This change would insert the expanded PATH at the time that the install process was run into the .bashrc . This wouldn't be a good idea. Maybe with more information about what actually broke it would be possible to find the correct fix.

**Comment by whossname** [comment]
I don't think I can really provide any useful information. All I know is I
needed to rebuild the path after running this code, add the /usr/bin and
/bin directories back in. I think there is a good chance I've missed a few
others.

**Comment by whossname** [comment]
Relevant part of my history, from starting the install to correcting the
file path:

 1683  sudo apt-get update
 1684  sudo apt-get install -y software-properties-common
 1685  sudo add-apt-repository -y ppa:hvr/ghc
 1686  sudo apt-get update
 1687  sudo apt-get install -y cabal-install-1.22 ghc-7.10.3
 1688  export
PATH="\$HOME/.cabal/bin:/opt/cabal/1.22/bin:/opt/ghc/7.10.3/bin:\$PATH"
 1689  EOF
 1690  export
PATH="\$HOME/.cabal/bin:/opt/cabal/1.22/bin:/opt/ghc/7.10.3/bin:\$PATH"
 1691  EOF
 1692  export
PATH=~/.cabal/bin:/opt/cabal/1.22/bin:/opt/ghc/7.10.3/bin:$PATH
 1693  sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80
--recv-keys 575159689BEFB442
 1694  sudo ls
 1695  export PATH=/usr/bin:$PATH
 1696  sudo ls
 1697  sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80
--recv-keys 575159689BEFB442
 1698  echo 'deb http://download.fpcomplete.com/ubuntu xenial main'|sudo
tee /etc/apt/sources.list.d/fpco.list
 1699  sudo apt-get update && sudo apt-get install stack -y
 1700  ls
 1701  export PATH=/bin:$PATH

**Comment by gbaz** [comment]
Ah so I think this can be closed as a transcription error? If you look at the instructions, the relevant line is for appending to a .bashrc file, not for direct entry into the console:

     cat >> ~/.bashrc <<EOF
     export PATH="\$HOME/.cabal/bin:/opt/cabal/1.22/bin:/opt/ghc/7.10.3/bin:\$PATH"
      EOF		      EOF

**Comment by whossname** [comment]
Ah, ok. Thanks for the help

**Pull request closed without merging**
