### PR TITLE
Added mentions to DataHaskell in the Community page

### PR DESCRIPTION
**Pull request by ocramz**

### CODE REVIEW

**Comment by relrod** [comment]
See comments in #193. I'm going to hold off (or let @gbaz merge if he wants). I think we should get a Committee opinion on what should be listed on the community page.

**Comment by ocramz** [comment]
@gbaz @relrod I added links to DataHaskell, a rather young but quite lively community dedicated to "data science", machine learning and scientific computation. We do have an official channel (the Gitter channel mentioned in the links), some collaborative projects on github and a .org landing page. We have ~ 120 registered users and a growing core team. We are, for all sensible definitions of the term, a Haskell community and we'd like to be mentioned on haskell.org .

**Comment by jaspervdj** [comment]
@ocramz @relrod I discussed with the Committee and the link belongs in the "Special Interest Groups" (`sigs`) list but not in the `online` list.

The other links in the `online` list are all about "general" Haskell, so it does not really belong there.  Furthermore, if people follow the link to the <http://www.datahaskell.org/> page, they can find a link to the Gitter community there.

**Comment by ocramz** [comment]
@jaspervdj Should I just edit out the`online` link then?

**Comment by jaspervdj** [comment]
@ocramz Yep, and after that it should be good to merge.

**Comment by ocramz** [comment]
@jaspervdj I've edited out the `online` link, as per request.

**Comment by jaspervdj** [comment]
@ocramz Thanks a lot!
@relrod Should be good to merge from the Committee's point of view.

**Comment by ocramz** [comment]
@relrod @gbaz could you merge please? Thanks!

**Pull request merged**
