### PR TITLE
Haskell Gitter

### PR DESCRIPTION
**Pull request by BRS999**
Haskell Gitter Community link

### CODE REVIEW

**Comment by relrod** [comment]
Waiting for review by @gbaz before I pull this in, because I'm not sure how official the gitter channel is and if we want to promote it or not.

**Comment by BRS999** [comment]
Sure thing. I spoke briefly with him about it. Although we didn't discuss adding it to the Haskell community page. We have 8 participants so far so I hope you will give it a chance!

**Comment by fafa2** [comment]
I was visiting haskell.org today and I noticed this commit.

I believe adding a community in the community section is warranted only when:
- it is in some kind "officiality" (haskell mailing lists, IRC) OR
- has a gigantic user base which we cannot ignore (reddit, fb, etc.)

Gitter doesn't fit any of this. Despite being advertised as "for open communities" it is closed sourced (SaaS), a big warning sign; also, on the traffic side, the last message in their main channel (#lobby), seems to be (as now) dated Jan 12 20:37

I am here to ask you to reconsider adding it.

**Comment by ocramz** [comment]
IMO the definition of "official channel" should be pragmatic and not ideological. A meeting channel for communities is wherever people meet to discuss. IRC has simply a long history of being a convenient and open venue for discussion, but is no more official than customary.
Gitter is a closed-source service, this is true, but it does support a large number of communities, and by this token should be considered an "official" channel as any other.

**Pull request merged**
