### PR TITLE
Make Rackspace logo white

### PR DESCRIPTION
**Pull request by ksheedlo**
In the current design of the site, the Rackspace logo is used against a
dark gray background, which obscures part of the logo. This change makes
both sides of the logo white so it will stand out.

### CODE REVIEW

**Comment by chrisdone** [comment]
Screenshot?

**Comment by ksheedlo** [comment]
@chrisdone my cabal dependencies are still installing, so I've only seen it yet in isolation. I will get you a screenshot as soon as I've built the site.

**Comment by ksheedlo** [comment]
I get this error when I try to run the server:

```
┌─[ken][ksheedlo-hackbook][±][fix-rackspace-logo ✓][2.0.0][~/hl]
└─▪ dist/build/hl/hl
hl: /Users/ken/hl/.cabal-sandbox/share/x86_64-osx-ghc-7.8.3/hl-0.0.0/static: getDirectoryContents: does not exist (No such file or directory)
```

The `.cabal-sandbox/share/x86_64-osx-ghc-7.8.3/hl-0.0.0` directory is not produced by `cabal build`, even though 0 is returned in the shell. Any idea what's going on?

**Comment by chrisdone** [comment]
Try `cabal install` within your sandbox to create the data-files directory.

**Comment by ksheedlo** [comment]
@chrisdone thanks, that worked! Here's the screenshot.

screen shot 2015-02-15 at 1 34 05 pm

**Comment by chrisdone** [comment]
Cool, looks good. I had the same complaint of the red/black on dark since it was added, but wasn't aware it was a trivially changed SVG. Merging.

**Comment by chrisdone** [comment]
Thanks!

**Pull request merged**
