### PR TITLE
Add Seattle Area Haskell Users' Group link

### PR DESCRIPTION
**Pull request by rcook**
Add Seattle Area Haskell Users' Group link to Community page

### CODE REVIEW

**Comment by rcook** [comment]
Thanks for merging this. How frequently is the Haskell.org web site refreshed? It looks like this change hasn't made it to the public web site yet despite having been submitted three months ago.

-Richard

**Comment by gbaz** [comment]
thanks for the kick :-)

**Comment by gbaz** [comment]
pushed now

**Comment by rcook** [comment]
Thanks!

**Comment by GetContented** [comment]
@gbaz ooh I wonder if you'd be able to merge mine, too? https://github.com/haskell-infra/hl/pull/154

**Pull request merged**
